# Generated by Django 3.0.3 on 2020-03-06 08:06

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_blog', '0007_blogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='wagtail_blog.BlogCategory'),
        ),
    ]
