# Generated by Django 3.0.3 on 2020-03-23 10:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_servicesnavbar_premium_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesnavbar',
            name='premium_service',
            field=wagtail.core.fields.StreamField([('service', wagtail.core.blocks.StructBlock([('service_name', wagtail.core.blocks.CharBlock()), ('return', wagtail.core.blocks.CharBlock(required=False)), ('S&P', wagtail.core.blocks.CharBlock(required=False)), ('intro', wagtail.core.blocks.CharBlock(required=False))]))], null=True),
        ),
    ]
