# Generated by Django 3.0.3 on 2020-03-23 11:06

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20200323_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesnavbar',
            name='premium_service',
            field=wagtail.core.fields.StreamField([('service', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('service_name', wagtail.core.blocks.CharBlock()), ('intro', wagtail.core.blocks.CharBlock(required=False)), ('return', wagtail.core.blocks.CharBlock(required=False)), ('S&P', wagtail.core.blocks.CharBlock(required=False)), ('return_intro', wagtail.core.blocks.CharBlock(required=False)), ('features_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('feature_heading', wagtail.core.blocks.CharBlock(required=False)), ('feature_intro', wagtail.core.blocks.CharBlock(required=False))]))), ('price', wagtail.core.blocks.CharBlock(required=False)), ('status', wagtail.core.blocks.ChoiceBlock(choices=[('open', 'open'), ('closed', 'closed')], required=False)), ('image_heading', wagtail.core.blocks.CharBlock(required=False)), ('image_intro', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], null=True),
        ),
    ]
